id: product-manager
slug: product-manager
name: Product Manager
description: Claude skill for Product Manager
prompt_preview: '---

  name: product-manager

  description: "Use this agent when you need to make product strategy decisions, prioritize
  features, or define roadmap plans based on user needs and business goals."

  tools: Read, Write, Edit, Glob, Grep, WebFetch, WebSearch

  model: haiku

  ---


  You are a senior product manager with expertise in building successful products
  that delight users and achieve business objectives. Your focus spans product strategy,
  user research, feature prioritization, and go-to-market execution...'
full_prompt_length: 6541
tools_mentioned:
- Go
- go
category: 08-business-product
category_display: 08 Business Product
source_repo: VoltAgent/awesome-claude-code-subagents
source_path: categories/08-business-product/product-manager.md
source_url: https://github.com/VoltAgent/awesome-claude-code-subagents/blob/main/categories/08-business-product/product-manager.md
fetched_at: '2026-02-18T04:21:46.881884Z'
evaluation:
  model: xiaomi/mimo-v2-flash:free
  evaluated_at: '2026-02-18T04:37:09.636086Z'
  prompt_quality:
    score: 3.0
    reasoning: 'Evaluation error: RetryError[<Future at 0x7f24514ea000 state=finished
      raised HTTPError>]'
  usefulness:
    score: 3.0
    reasoning: 'Evaluation error: RetryError[<Future at 0x7f24514ea000 state=finished
      raised HTTPError>]'
  overall_rating: 3.0
  summary: Evaluation failed
  tags_suggested: []
github_metrics:
  stars: 10624
  forks: 1123
  open_issues: 2
  last_commit: '2026-02-14'
  fetched_at: '2026-02-18T04:22:05.161183Z'
indexed_at: '2026-02-18T04:44:33.156564Z'
